#!/bin/sh

# A hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed. This hook checks the keychain for jss-dev and jss-prod instances
# and if they exist attempts to run the sync.py script against your dev
# instance. If successful, the script will then attempt to upload to prod.
# This script can and probably should be modified to suit your specific needs.
# NOTE: If you are using some CI platform or there is more than 1 person
# working on this repo the script should probably not be used and you should
# use whatever tool your CI server provides.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>

remote="$1"
url="$2"


DEV_URL=`security find-generic-password -l "git2jss-dev" -g 2>&1 | grep 'svce' | cut -d \" -f 4`
DEV_ACCT=`security find-generic-password -l "git2jss-dev" -g 2>&1 | grep 'acct' | cut -d \" -f 4`
DEV_PASS=`security find-generic-password -l "git2jss-dev" -w`

PROD_URL=`security find-generic-password -l "git2jss-dev" -g 2>&1 | grep 'svce' | cut -d \" -f 4`
PROD_ACCT=`security find-generic-password -l "git2jss-dev" -g 2>&1 | grep 'acct' | cut -d \" -f 4`
PROD_PASS=`security find-generic-password -l "git2jss-dev" -w`

branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')


# Attempt the push to dev
echo "This hook has been moved under the tools/hooks/ directory, please use the updated path as this hook will be removed in future versions"
./sync.py --url "$DEV_URL" --username "$DEV_ACCT" --password "$DEV_PASS"
err=$?

if [[ $err -eq 0 ]]; then
    echo "Push to dev successful, attempting push to prod."
    # but we aren't ready for prod ;)
    exit 0
else
    echo "Push to dev returned an error, canceling push."
    echo "Remote not updated, please correct the errors before continuing"
    exit 1
fi

